import type { Metadata } from "next";
import Link from "next/link";
import { SiteNav } from "@/components/marketing/site-nav";
import { SiteFooter } from "@/components/marketing/site-footer";
import { ButtonLink } from "@/components/ui/button";
import { CASE_STUDIES } from "@/lib/marketing/customers";

export const metadata: Metadata = { title: "Customers", description: "How service businesses use ClientFold to keep client work moving.", alternates: { canonical: "/customers" }, robots: { index: false, follow: false } };

export default function CustomersPage() {
  return <div className="min-h-screen bg-[#f7f6f1] text-[#292b26]"><SiteNav/><main><header className="border-b border-[#d9d8d2] bg-[#f3f2ed]"><div className="container grid gap-8 py-16 sm:py-24 lg:grid-cols-[0.72fr_1.28fr]"><p className="text-[10px] uppercase tracking-[0.16em] text-[#697363]">Customer stories</p><div data-reveal="soft"><h1 className="max-w-2xl text-balance text-4xl font-medium leading-tight tracking-[-0.045em] sm:text-5xl">Built around the way good client work actually happens.</h1><p className="mt-5 max-w-lg text-sm leading-6 text-[#71736b]">Real stories only. No invented logos, inflated numbers or anonymous testimonials.</p></div></div></header><section className="container py-14 sm:py-20">{CASE_STUDIES.length === 0 ? <div className="grid border border-[#d5d4cd] lg:grid-cols-[0.82fr_1.18fr]" data-reveal><div className="border-b border-[#d5d4cd] p-8 lg:border-b-0 lg:border-r lg:p-12"><p className="text-[9px] uppercase tracking-[0.15em] text-[#697363]">Early access</p><h2 className="mt-6 max-w-sm text-2xl font-medium tracking-[-0.03em]">The first case studies are being documented now.</h2><p className="mt-4 max-w-sm text-[12px] leading-6 text-[#74766e]">We will publish the workflow, the before-and-after and the measurable result—once each customer has reviewed and approved it.</p><ButtonLink href="/waitlist" size="lg" className="mt-7 bg-[#2d302a] hover:bg-[#44473f]">Join the waitlist</ButtonLink></div><div className="bg-[#eeede7] p-8 lg:p-12"><p className="text-[9px] uppercase tracking-[0.15em] text-[#8a8c83]">What every story will show</p><div className="mt-8 space-y-3">{[["01","The old client workflow"],["02","What moved into ClientFold"],["03","Where chasing was removed"],["04","The result, in the customer's words"]].map(([n,text])=><div key={n} className="flex items-center gap-4 border-b border-[#d8d7d0] pb-3 text-xs"><span className="font-mono text-[9px] text-[#999b93]">{n}</span><span>{text}</span><span className="ml-auto size-1.5 rounded-full bg-[#7a856f]"/></div>)}</div></div></div> : <div className="grid gap-px border border-[#d5d4cd] bg-[#d5d4cd] sm:grid-cols-2">{CASE_STUDIES.map((study)=><Link key={study.slug} href={`/customers/${study.slug}`} data-reveal="soft" className="min-h-60 bg-[#f7f6f1] p-7 transition-colors hover:bg-[#f0efe9]"><p className="text-[9px] uppercase tracking-[0.14em] text-[#697363]">Customer story</p><h2 className="mt-14 text-xl font-medium">{study.customer}</h2><p className="mt-3 text-[11px] leading-5 text-[#777970]">{study.summary}</p></Link>)}</div>}</section></main><SiteFooter/></div>;
}
