import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Refund and Cancellation Policy", description: "How ClientFold subscription cancellations, billing corrections and refund requests work.", alternates: { canonical: "/refunds" } };

const sections: LegalSection[] = [
  { title: "Scope", content: <><p>This policy applies to subscription fees paid directly to ClientFold. It does not govern invoice payments made by a client to a ClientFold customer through Stripe; disputes about those invoices must be raised with the business that issued them.</p><p>This policy adds to, and does not replace, rights that cannot be excluded under applicable law.</p></> },
  { title: "Cancel at any time", content: <><p>You may cancel a paid subscription through billing settings or by contacting <a href="mailto:billing@useclientfold.com">billing@useclientfold.com</a>. Cancellation stops the next renewal. Unless we tell you otherwise, paid access continues until the end of the billing period and the account is not charged again.</p><p>Deleting a workspace or stopping use does not by itself cancel a subscription. Please use the billing cancellation control or obtain written confirmation from us.</p></> },
  { title: "First-purchase promise", content: <><p>If the first paid ClientFold subscription is not right for you, request a refund within 14 days after the initial charge. We will refund that subscription fee to the original payment method. This voluntary promise applies once per customer or substantially related organisation and does not cover usage charges, third-party fees or abuse.</p><p>Where mandatory consumer cancellation rights apply, we will honour them even if they are more favourable than this promise. If you asked us to begin supplying a service during a statutory cancellation period, the law may allow a proportionate charge for service already supplied.</p></> },
  { title: "Renewals and plan changes", content: <><p>Subscription charges are normally non-refundable after a renewal because access is reserved for the new billing period. If you forgot to cancel, contact us within 14 days of the renewal. Where the workspace has not materially used the paid service since renewal, we will normally approve a refund as a gesture of fairness.</p><p>Plan upgrades may take effect immediately and be prorated. Downgrades normally take effect at the next renewal. The billing screen or checkout confirmation will show the timing before you confirm.</p></> },
  { title: "Billing errors and service problems", content: <><p>Contact us promptly about duplicate charges, an incorrect amount, a charge after confirmed cancellation or suspected unauthorised payment. We will investigate and correct confirmed errors.</p><p>If a material, prolonged service failure prevents reasonable use of the paid service, we may provide a proportionate refund or account credit. Scheduled maintenance, third-party outages outside our reasonable control, and problems caused by a customer’s device, connection or configuration do not automatically qualify.</p></> },
  { title: "How to request a refund", content: <><p>Email <a href="mailto:billing@useclientfold.com">billing@useclientfold.com</a> or use the <a href="/contact?topic=billing">billing contact form</a>. Include the account email, organisation name, invoice or receipt reference, charge date and a short explanation. Do not send full payment-card details.</p><p>We aim to acknowledge requests within two working days. Approved refunds are sent to the original payment method. Your bank or payment provider controls how long the credit takes to appear.</p></> },
  { title: "Chargebacks and contact", content: <><p>Please contact us before starting a payment dispute so we have a fair opportunity to investigate. Nothing here prevents you from using a lawful chargeback or other remedy. Fraudulent or abusive disputes may lead to account restriction and recovery of amounts properly due.</p><p>Questions about this policy can be sent to <a href="mailto:billing@useclientfold.com">billing@useclientfold.com</a>.</p></> },
];

export default function RefundsPage() { return <LegalPage activeHref="/refunds" documentNumber="06" title="Refund & Cancellation Policy" summary="A straightforward explanation of how to stop renewal, when a refund is available and how we correct billing mistakes." contactEmail="billing@useclientfold.com" updated="24 August 2026" sections={sections} />; }
