import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { CookieSettingsButton } from "@/components/marketing/cookie-settings-button";

export const metadata: Metadata = { title: "Cookie Notice", description: "How ClientFold uses cookies and how to control them.", alternates: { canonical: "/cookies" } };

const sections: LegalSection[] = [
  { title: "What cookies are", content: <><p>Cookies are small text files stored on a browser or device. They help websites remember information, keep sessions secure and—when permitted—understand how a site is used. Similar local storage technologies may operate in the same way.</p></> },
  { title: "How we use them", content: <><p>ClientFold uses essential cookies for login sessions, portal access and recording privacy choices. These are necessary to provide requested features. Analytics and advertising measurement are optional and remain off until the relevant consent is given.</p><p>Rejecting optional cookies does not stop you from using the core service.</p></> },
  { title: "Cookie list", content: <div className="overflow-x-auto"><table className="w-full min-w-[520px] border-collapse text-left text-[11px]"><thead><tr className="border-b border-[#d6d5ce] text-[#4f524a]"><th className="py-2 pr-3 font-medium">Cookie</th><th className="py-2 pr-3 font-medium">Purpose</th><th className="py-2 pr-3 font-medium">Type</th><th className="py-2 font-medium">Duration</th></tr></thead><tbody className="divide-y divide-[#dfded8]"><tr><td className="py-3 pr-3 font-mono text-[9px]">cf_session</td><td className="py-3 pr-3">Keeps an account user signed in securely.</td><td className="py-3 pr-3">Essential</td><td className="py-3">30 days</td></tr><tr><td className="py-3 pr-3 font-mono text-[9px]">cf_portal</td><td className="py-3 pr-3">Keeps an invited client signed into their portal.</td><td className="py-3 pr-3">Essential</td><td className="py-3">30 days</td></tr><tr><td className="py-3 pr-3 font-mono text-[9px]">cf_consent_set</td><td className="py-3 pr-3">Remembers that a privacy choice was made.</td><td className="py-3 pr-3">Essential</td><td className="py-3">180 days</td></tr><tr><td className="py-3 pr-3 font-mono text-[9px]">cf_consent_analytics</td><td className="py-3 pr-3">Remembers the analytics preference.</td><td className="py-3 pr-3">Essential preference</td><td className="py-3">180 days</td></tr><tr><td className="py-3 pr-3 font-mono text-[9px]">cf_consent_advertising</td><td className="py-3 pr-3">Remembers the advertising measurement preference.</td><td className="py-3 pr-3">Essential preference</td><td className="py-3">180 days</td></tr><tr><td className="py-3 pr-3 font-mono text-[9px]">cf_attrib</td><td className="py-3 pr-3">Connects consented visits with campaign and referral information.</td><td className="py-3 pr-3">Analytics</td><td className="py-3">365 days</td></tr></tbody></table></div> },
  { title: "Third-party services", content: <><p>Stripe may set cookies on its hosted payment or account-onboarding pages for fraud prevention, security and payment processing. Those pages are governed by Stripe’s own notices. Our transactional email provider does not set cookies on ClientFold pages.</p></> },
  { title: "Manage your choice", content: <><p>You can accept all optional purposes, allow analytics only, or keep only essential cookies. You can revisit the choice at any time.</p><CookieSettingsButton className="mt-4 border border-[#c8c7c0] bg-[#f3f2ed] px-4 py-2 text-[11px] font-medium text-[#3a3d35] hover:bg-white"/><p>You can also delete cookies through your browser. Blocking essential cookies may prevent sign-in or portal access.</p></> },
  { title: "Updates and contact", content: <><p>We review this notice when our technology or legal obligations change. Questions can be sent to <a href="mailto:privacy@clientfold.com">privacy@clientfold.com</a>.</p></> },
];

export default function CookiesPage() { return <LegalPage title="Cookie Notice" summary="A practical list of the cookies ClientFold uses, what each one does and how long it remains on your device." sections={sections}/>; }
