import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Security and Responsible Disclosure", description: "How ClientFold protects workspaces and how to report a potential vulnerability safely.", alternates: { canonical: "/security" } };

const sections: LegalSection[] = [
  { title: "Our approach", content: <><p>ClientFold uses layered technical and organisational measures intended to protect account, project and client information. No internet service can promise absolute security, so we combine preventive controls with monitoring, limited access and a process for investigating reports.</p><p>This page is a plain-language security overview, not a certification, warranty or guarantee that incidents cannot occur.</p></> },
  { title: "Product safeguards", content: <><ul><li>Tenant-sensitive database access is kept server-side and scoped to the relevant organisation.</li><li>Account and client-portal sessions use secure tokens and expiry controls.</li><li>Payment-card details are handled by Stripe rather than stored by ClientFold.</li><li>Integration webhooks use signature verification or signing where supported.</li><li>Files are served through controlled application routes and authorised storage access.</li><li>Security and activity records help investigate important account events.</li></ul></> },
  { title: "Your responsibilities", content: <><p>Use a unique password, protect email accounts connected to ClientFold, limit team access to people who need it and remove former members promptly. Treat client portal links as confidential and review sharing before uploading sensitive material.</p><p>Contact us immediately if you suspect account access, a portal link or an integration credential has been compromised.</p></> },
  { title: "Report a vulnerability", content: <><p>Send a concise report to <a href="mailto:security@useclientfold.com">security@useclientfold.com</a> with the affected page or feature, reproduction steps, likely impact and any non-sensitive evidence. Do not include secrets in an initial message.</p><p>We aim to acknowledge credible security reports within two working days, investigate according to risk and keep the reporter informed when practical.</p></> },
  { title: "Safe research boundaries", content: <><p>When testing ClientFold, use only accounts and data you own or have explicit permission to test. Stop if you access another person’s data. Do not degrade the service, use automated high-volume testing, persist after proving a vulnerability, access unnecessary data, attempt social engineering, or publicly disclose an unresolved issue.</p><p>Good-faith research that respects these boundaries and gives us reasonable time to respond will not be treated as a violation of our Acceptable Use Policy solely because it identified a security weakness. This is not permission to break the law or access third-party systems.</p></> },
  { title: "Incidents and updates", content: <><p>If we confirm a personal-data breach or security incident, we will contain and investigate it, preserve relevant records, and notify affected customers or authorities where required by law. We review safeguards as the service changes and may update this page to reflect material improvements or new risks.</p></> },
];

export default function SecurityPage() { return <LegalPage activeHref="/security" documentNumber="07" eyebrow="ClientFold trust" title="Security & Responsible Disclosure" summary="The safeguards, shared responsibilities and reporting path that help protect ClientFold workspaces and the people using them." contactEmail="security@useclientfold.com" updated="24 August 2026" sections={sections} />; }
