import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Terms of Service", description: "The terms governing use of ClientFold.", alternates: { canonical: "/terms" } };

const sections: LegalSection[] = [
  { title: "About these terms", content: <><p>These Terms of Service form an agreement between you and ClientFold, the operator identified on your order form or subscription receipt. They apply when you access or use ClientFold, including its client portals, file tools, approvals, messaging and invoicing features.</p><p>If you use ClientFold for an organisation, you confirm that you can accept these terms for that organisation. The service is intended for business and professional use by people aged 18 or over.</p></> },
  { title: "Your account", content: <><p>You must provide accurate account information, keep login details secure and promptly tell us about suspected unauthorised access. You are responsible for activity under your account and for managing who can access your organisation and client portals.</p><p>Do not share invitation links with unintended recipients. Client access can be revoked from the service.</p></> },
  { title: "The service", content: <><p>ClientFold provides tools for managing client projects, approvals, files, messages, reminders and invoices. We may improve or change features over time. We will not materially reduce the core functionality of a paid plan during its current billing period without reasonable notice.</p><p>ClientFold is not an accounting, legal, tax or regulated payment service. Invoices and records created in the service do not replace professional advice or your own record-keeping obligations.</p></> },
  { title: "Your content and clients", content: <><p>You retain ownership of content uploaded to ClientFold. You grant us the limited rights needed to host, process, transmit and display that content to provide and secure the service.</p><p>You are responsible for having a lawful basis to add client contacts and content, for configuring appropriate access, and for the legality and accuracy of material you send through ClientFold. Where we process client personal data on your instructions, you act as controller and we act as processor.</p></> },
  { title: "Fees, renewals and cancellation", content: <><p>Prices, plan limits and billing intervals are shown before purchase. Paid subscriptions renew automatically for the selected billing period until cancelled. Taxes may be added where required.</p><p>You may cancel at any time; access to paid features continues until the end of the paid billing period unless stated otherwise. Except where law requires, fees already paid are non-refundable. We will give reasonable notice of price changes before they apply to a renewal.</p></> },
  { title: "Payments and third parties", content: <><p>Subscription and client-invoice payments may be handled by Stripe. Connected payment accounts are subject to Stripe’s terms. Other providers may supply hosting, storage and transactional email. We are not responsible for third-party services outside our control, but we remain responsible for selecting and overseeing our processors as required by data protection law.</p></> },
  { title: "Acceptable use", content: <><p>You must follow our <a href="/acceptable-use">Acceptable Use Policy</a>. You must not misuse the service, interfere with its security, upload unlawful or harmful material, or use it to violate another person’s rights.</p><p>We may remove content or restrict access where reasonably necessary to protect users, the service or third parties, or to comply with law.</p></> },
  { title: "Confidentiality and security", content: <><p>Each party must protect the other’s confidential information and use it only for the agreement. This does not cover information already public through no breach, independently developed, or lawfully obtained elsewhere.</p><p>We use reasonable technical and organisational safeguards. No online service can guarantee absolute security, so you should maintain appropriate backups of business-critical material.</p></> },
  { title: "Suspension and termination", content: <><p>You may stop using the service at any time. We may suspend access for a material breach, non-payment, a credible security risk or unlawful use. Where practical, we will give notice and an opportunity to resolve the issue.</p><p>After termination, your right to use the service ends. Provisions that by their nature should continue—including ownership, confidentiality, payment obligations and liability limits—will survive.</p></> },
  { title: "Warranties and liability", content: <><p>We provide the service with reasonable care and skill. Subject to rights that cannot legally be excluded, the service is provided without other implied warranties and may occasionally be unavailable.</p><p>Neither party is liable for indirect or consequential loss, loss of profit, revenue, goodwill or anticipated savings. Our total liability arising from the service will not exceed the fees you paid for it in the 12 months before the event giving rise to the claim. Nothing limits liability that cannot lawfully be limited, including fraud, fraudulent misrepresentation, or death or personal injury caused by negligence.</p></> },
  { title: "Law, changes and contact", content: <><p>These terms are governed by the laws of England and Wales, and the courts of England and Wales have jurisdiction, unless mandatory law requires otherwise. We may update these terms to reflect service or legal changes. We will give reasonable notice of material changes.</p><p>Questions may be sent to <a href="mailto:legal@clientfold.com">legal@clientfold.com</a>.</p></> },
];

export default function TermsPage() { return <LegalPage title="Terms of Service" summary="The agreement for using ClientFold. These terms explain account responsibilities, subscriptions, ownership, acceptable use and the limits of the service." sections={sections}/>; }
