import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Privacy Notice", description: "How ClientFold collects, uses and protects personal information.", alternates: { canonical: "/privacy" } };

const sections: LegalSection[] = [
  { title: "Who this notice covers", content: <><p>ClientFold is responsible for personal information used to operate accounts, subscriptions, our website and communications. Contact us at <a href="mailto:privacy@clientfold.com">privacy@clientfold.com</a>.</p><p>When a business uses ClientFold to manage its own clients, that business usually decides why and how client information is used. It is the controller and ClientFold acts as its processor. Client users should first direct project-data requests to the business that invited them.</p></> },
  { title: "Information we collect", content: <><ul><li>Account and organisation details, such as name, email, business name, role, website and billing contact.</li><li>Client workspace content, including contacts, projects, messages, files, comments, approvals, invoices and activity history.</li><li>Security and device information, such as session identifiers, browser information, timestamps and hashed network identifiers used for audit records.</li><li>Billing and transaction references. Payment-card details are entered with Stripe and are not stored by ClientFold.</li><li>Website and campaign information, such as pages visited, referral source and campaign parameters, where analytics consent is given.</li><li>Communications and support requests you send to us.</li></ul></> },
  { title: "How and why we use information", content: <><ul><li><b>Contract:</b> to create accounts, provide workspaces, deliver notifications, process subscriptions and support users.</li><li><b>Legitimate interests:</b> to secure and improve the service, prevent abuse, understand aggregate product use and communicate about closely related service matters.</li><li><b>Consent:</b> for non-essential analytics or advertising measurement. Consent can be changed at any time through Cookie settings.</li><li><b>Legal obligation:</b> to keep required financial records, respond to lawful requests and meet regulatory duties.</li></ul><p>We do not sell personal information or use client workspace content for third-party advertising.</p></> },
  { title: "How information is shared", content: <><p>Information is shared only as needed with authorised members of your organisation and invited client users; service providers that supply hosting, object storage, email delivery, security and customer support; Stripe for subscription and invoice-payment services; professional advisers; and public authorities where legally required.</p><p>Configured providers may include Stripe for payments, Resend for transactional email, and an S3-compatible storage provider. We require service providers to protect information and use it only for agreed services.</p></> },
  { title: "International transfers", content: <><p>Some providers may process information outside the United Kingdom. Where required, we use recognised safeguards such as adequacy regulations or approved contractual protections and carry out appropriate transfer assessments.</p></> },
  { title: "How long we keep information", content: <><p>We retain account and workspace information while an account is active and for a limited period afterwards to support recovery, resolve disputes and meet legal obligations. Financial records may be kept for longer where tax or accounting law requires. Security logs and consent records are kept only for a proportionate period.</p><p>Retention can also depend on instructions from the organisation controlling a client workspace. When information is no longer required, it is deleted or anonymised, including through the applicable backup cycle.</p></> },
  { title: "Security", content: <><p>We use access controls, signed sessions, tenant separation, restricted file links, encryption in transit and audit records designed to protect information. We review access and limit personnel and provider access to what is needed. No system is completely secure; please report concerns promptly to <a href="mailto:security@clientfold.com">security@clientfold.com</a>.</p></> },
  { title: "Your rights", content: <><p>Depending on the circumstances, you may have rights to be informed, access personal information, correct it, request deletion or restriction, object to processing, obtain portable data and withdraw consent. You may also complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" rel="noreferrer">ico.org.uk</a>.</p><p>To make a request, email <a href="mailto:privacy@clientfold.com">privacy@clientfold.com</a>. We may need to verify your identity. If the information belongs to a customer-controlled workspace, we may refer the request to that customer.</p></> },
  { title: "Cookies and similar technology", content: <><p>Essential cookies keep sessions and preferences working. We use non-essential analytics or advertising measurement only after the relevant choice. See the <a href="/cookies">Cookie Notice</a> or open Cookie settings in the footer.</p></> },
  { title: "Children, changes and contact", content: <><p>ClientFold is a business service and is not directed to children. We may update this notice when the service or law changes and will highlight material changes where appropriate.</p><p>Privacy questions can be sent to <a href="mailto:privacy@clientfold.com">privacy@clientfold.com</a> or ClientFold, United Kingdom.</p></> },
];

export default function PrivacyPage() { return <LegalPage title="Privacy Notice" summary="This notice explains what personal information ClientFold handles, why it is used, who it may be shared with and the choices available to you." sections={sections}/>; }
