import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Accessibility Statement", description: "How ClientFold approaches accessibility, known limitations and how to request help.", alternates: { canonical: "/accessibility" } };

const sections: LegalSection[] = [
  { title: "Our commitment", content: <><p>ClientFold wants its website, account workspace and client portals to be usable by as many people as possible, including people who use assistive technology. Accessibility is part of our product work, not a one-time certification exercise.</p><p>We aim to follow the Web Content Accessibility Guidelines (WCAG) 2.2 Level AA. This statement describes our present approach and does not claim that every page fully conforms.</p></> },
  { title: "What we design for", content: <><p>We work to provide:</p><ul><li>semantic headings, landmarks, labels and controls that work with assistive technology;</li><li>keyboard access and visible focus states for interactive features;</li><li>clear language, instructions and error messages;</li><li>sufficient colour contrast and information that does not rely on colour alone;</li><li>responsive layouts that support zoom and different screen sizes; and</li><li>reduced-motion behaviour where device preferences request it.</li></ul></> },
  { title: "Known limitations", content: <><p>ClientFold is in early access and some areas may not yet meet our intended standard. In particular, complex file previews, content uploaded by customers, some third-party payment or account-onboarding pages, and dense interactive workspace views may present barriers for some users.</p><p>Third-party content and customer-uploaded files are not always under our control. We still want to hear when those experiences block a task so we can offer an alternative or work with the relevant provider.</p></> },
  { title: "Compatibility", content: <><p>ClientFold is designed for current versions of major browsers and operating-system accessibility features. Results can vary with older browsers, unusual browser extensions and different assistive-technology combinations.</p><p>If a feature does not work with your setup, tell us the browser, device and assistive technology you use where you are comfortable doing so. You do not need to disclose a disability.</p></> },
  { title: "Get help or report a barrier", content: <><p>Email <a href="mailto:accessibility@useclientfold.com">accessibility@useclientfold.com</a> or use our <a href="/contact?topic=support">contact form</a>. Describe the page, the task you were trying to complete and what happened. We aim to acknowledge accessibility reports within two working days.</p><p>We can provide reasonable alternative support, such as explaining a workflow, accepting information through another channel or supplying a document in a different format where practical.</p></> },
  { title: "How we review accessibility", content: <><p>We include keyboard use, focus order, labels, contrast, zoom and reduced-motion checks in product review. We plan deeper assistive-technology testing as the early-access product matures and will update this statement when our testing, known limitations or target standard changes.</p><p>This statement was prepared with reference to WCAG 2.2 and W3C guidance for accessibility statements.</p></> },
];

export default function AccessibilityPage() { return <LegalPage activeHref="/accessibility" documentNumber="05" eyebrow="ClientFold standards" title="Accessibility Statement" summary="Our approach to making ClientFold usable with different devices, interaction methods and assistive technologies—and how to tell us when we fall short." contactEmail="accessibility@useclientfold.com" updated="24 August 2026" sections={sections} />; }
